name: Update GitHub Pages

on:
  workflow_dispatch: # Allow Manual Triggering
  schedule:
    # Run the workflow once a day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python scripts
      - name: Run scripts
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python get-data.py
          python generate-html.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add index.html
          git commit -m "Automated update: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
